-- ============================================================================
-- Migration 00054: Phase 2.3 — Daily COD cash reconciliation
-- ============================================================================
--
-- BUSINESS CASE:
--   COD operations live or die on cash reconciliation. At end of day, ops needs:
--     • Total cash collected per delivery agent
--     • Bank deposit confirmation per agent
--     • Variance flag when deposit != collected
--   Today payment_events has the raw collection log but no daily rollup, no
--   deposit tracking, no variance detection. This migration adds all three.
--
-- TABLE: cod_daily_reconciliation
--   One row per (date, agent_id). Auto-generated by the aggregator job from
--   payment_events with event_type='cod_collection_confirmed'.
--   Bank deposit fields are filled by ops via the admin UI (Step 2.3.c).
--   Variance is GENERATED — no risk of staleness.
--
-- RPC: aggregate_cod_collections_for_date(p_date)
--   Idempotent. Re-running for the same date refreshes the rollup. Preserves
--   any deposit info already entered by ops (only updates collection totals).
--
-- IDEMPOTENCY:
--   CREATE TABLE IF NOT EXISTS + CREATE OR REPLACE FUNCTION.
-- ============================================================================

-- ── 1. Table ─────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.cod_daily_reconciliation (
  id              uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  date            date NOT NULL,
  agent_id        uuid REFERENCES auth.users(id) ON DELETE SET NULL,
  total_collected numeric(12,2) NOT NULL DEFAULT 0,
  order_count     integer       NOT NULL DEFAULT 0,
  -- Reconciliation (filled by ops via admin UI)
  bank_deposit_amount numeric(12,2),
  bank_deposit_ref    text,
  deposited_at        timestamptz,
  -- Status mirrors the deposit lifecycle
  status              text NOT NULL DEFAULT 'pending'
                          CHECK (status IN ('pending','reconciled','variance')),
  -- Computed at write time so it never drifts from the inputs
  variance_amount     numeric(12,2) GENERATED ALWAYS AS (
    COALESCE(bank_deposit_amount, 0::numeric) - total_collected
  ) STORED,
  notes               text,
  created_at          timestamptz NOT NULL DEFAULT now(),
  updated_at          timestamptz NOT NULL DEFAULT now()
);

-- Allow only one rollup per (date, agent). NULL agent_id is collapsed to
-- a single "system / unknown" row per date.
CREATE UNIQUE INDEX IF NOT EXISTS cod_recon_date_agent_uniq
  ON public.cod_daily_reconciliation (date, COALESCE(agent_id, '00000000-0000-0000-0000-000000000000'::uuid));

CREATE INDEX IF NOT EXISTS cod_recon_status_idx
  ON public.cod_daily_reconciliation (status, date);

-- ── 2. updated_at trigger ────────────────────────────────────────────────────
DROP TRIGGER IF EXISTS trg_cod_recon_updated_at ON public.cod_daily_reconciliation;
CREATE TRIGGER trg_cod_recon_updated_at
  BEFORE UPDATE ON public.cod_daily_reconciliation
  FOR EACH ROW
  EXECUTE FUNCTION public.set_updated_at();

-- ── 3. RLS — admin only ──────────────────────────────────────────────────────
ALTER TABLE public.cod_daily_reconciliation ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Admins manage cod reconciliation" ON public.cod_daily_reconciliation;
CREATE POLICY "Admins manage cod reconciliation"
  ON public.cod_daily_reconciliation
  FOR ALL
  USING      (public.is_admin())
  WITH CHECK (public.is_admin());

DROP POLICY IF EXISTS "Service role manages cod reconciliation" ON public.cod_daily_reconciliation;
CREATE POLICY "Service role manages cod reconciliation"
  ON public.cod_daily_reconciliation
  FOR ALL
  USING      (auth.role() = 'service_role')
  WITH CHECK (auth.role() = 'service_role');

-- ── 4. RPC: aggregate for one date ──────────────────────────────────────────
CREATE OR REPLACE FUNCTION public.aggregate_cod_collections_for_date(
  p_date date
)
RETURNS integer
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_rows integer;
BEGIN
  -- Aggregate one rollup row per agent_id for the given date.
  WITH agg AS (
    SELECT
      p_date                    AS date,
      pe.actor_id               AS agent_id,
      SUM(pe.amount)::numeric(12,2) AS total_collected,
      COUNT(DISTINCT pe.order_id)   AS order_count
    FROM public.payment_events pe
    WHERE pe.event_type = 'cod_collection_confirmed'
      AND pe.amount IS NOT NULL
      AND (pe.created_at AT TIME ZONE 'UTC')::date = p_date
    GROUP BY pe.actor_id
  )
  INSERT INTO public.cod_daily_reconciliation AS r (
    date, agent_id, total_collected, order_count, status
  )
  SELECT date, agent_id, total_collected, order_count,
         -- Preserve 'reconciled' once set elsewhere; new rows start 'pending'.
         'pending'::text
  FROM agg
  ON CONFLICT (date, COALESCE(agent_id, '00000000-0000-0000-0000-000000000000'::uuid))
  DO UPDATE SET
    total_collected = EXCLUDED.total_collected,
    order_count     = EXCLUDED.order_count,
    updated_at      = now()
  WHERE
    -- Only refresh the collection totals; don't touch deposit/status fields
    -- that ops may have edited.
    r.total_collected IS DISTINCT FROM EXCLUDED.total_collected
    OR r.order_count   IS DISTINCT FROM EXCLUDED.order_count;

  GET DIAGNOSTICS v_rows = ROW_COUNT;
  RETURN v_rows;
END;
$$;

-- ── 5. RPC: aggregate yesterday (convenience for cron) ──────────────────────
CREATE OR REPLACE FUNCTION public.aggregate_cod_collections_yesterday()
RETURNS integer
LANGUAGE sql
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT public.aggregate_cod_collections_for_date(
    ((now() AT TIME ZONE 'UTC')::date - 1)
  );
$$;

-- ── 6. Grants — admin / service_role only ───────────────────────────────────
REVOKE ALL ON public.cod_daily_reconciliation FROM anon, authenticated;
GRANT SELECT, UPDATE ON public.cod_daily_reconciliation TO authenticated;
-- (admins are 'authenticated' too; RLS gates them via is_admin())
GRANT ALL    ON public.cod_daily_reconciliation TO service_role;

REVOKE ALL ON FUNCTION public.aggregate_cod_collections_for_date(date) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.aggregate_cod_collections_yesterday()    FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.aggregate_cod_collections_for_date(date) TO service_role;
GRANT EXECUTE ON FUNCTION public.aggregate_cod_collections_yesterday()    TO service_role;
